# Generated by Django 2.1 on 2019-06-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190603_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to='ilan_resmi'),
        ),
    ]
