# Generated by Django 2.1 on 2019-06-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190603_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='ilan_resmi'),
        ),
    ]
