# Generated by Django 2.1 on 2019-06-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190609_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='relevance',
            field=models.IntegerField(choices=[('', 'Hepsi'), (1, 'Satılık'), (2, 'Kiralık')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[('', 'Hepsi'), (1, 'Eğlence'), (2, 'Kitap'), (3, 'Ulaşım'), (4, 'Hizmet')], default=1),
        ),
    ]
