# Generated by Django 2.1 on 2019-06-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190609_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mini_content',
            field=models.CharField(default='', max_length=100),
        ),
    ]
