# Generated by Django 2.1 on 2019-06-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_mini_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mini_content',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
