# Generated by Django 2.1 on 2019-09-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20190609_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='relevance',
            new_name='Kategori_1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='Kategori_2',
        ),
    ]
