# Generated by Django 2.1 on 2019-09-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20190914_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='iletisim',
            field=models.CharField(default='BURAYA İLETİŞİM GİR', max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='mini_content',
            field=models.CharField(default='', max_length=40),
        ),
    ]
