# Generated by Django 2.1 on 2019-09-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20190919_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Aktiflik',
            field=models.IntegerField(choices=[(1, 'AKTİF'), (2, 'KULLANIM DIŞI')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='iletisim',
            field=models.CharField(default='', max_length=100),
        ),
    ]
