# Generated by Django 2.1 on 2019-09-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20190920_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Aktiflik',
            field=models.CharField(choices=[(1, 'AKTİF'), (2, 'KULLANIM DIŞI')], default='AKTİF', max_length=100),
        ),
    ]
