# Generated by Django 2.1 on 2019-09-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20190920_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Aktiflik',
            field=models.IntegerField(choices=[(1, 'AKTİF'), (2, 'KULLANIM DIŞI')], default=1),
        ),
    ]
