# Generated by Django 2.1 on 2019-09-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20190920_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Aktiflik',
            field=models.IntegerField(choices=[(1, 'Aktif'), (2, 'Pasif')], default=1),
        ),
    ]
