# Generated by Django 2.1 on 2019-06-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190608_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='relevance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
