# Generated by Django 2.1 on 2019-09-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190608_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='SALAK', max_length=10),
        ),
    ]
