# Generated by Django 2.1 on 2019-09-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imza',
            field=models.BooleanField(default=False),
        ),
    ]
