# Generated by Django 2.1 on 2019-09-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_imza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imza',
            field=models.BooleanField(),
        ),
    ]
