# Generated by Django 2.1 on 2019-09-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190923_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='imza',
        ),
    ]
